import express from "express";
import cors from "cors";
import { spawn } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 8787;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

function runCli(args) {
  return new Promise((resolve, reject) => {
    const proc = spawn("python", args, {
      cwd: repoRoot,
      shell: false,
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (data) => {
      stdout += data.toString();
    });

    proc.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    proc.on("error", (err) => {
      reject({
        error: "Failed to start CLI process",
        detail: err.message,
      });
    });

    proc.on("close", (code) => {
      if (code !== 0) {
        return reject({
          error: "CLI execution failed",
          code,
          stderr,
          stdout,
        });
      }

      try {
        resolve(JSON.parse(stdout));
      } catch {
        reject({
          error: "Invalid JSON from CLI",
          raw: stdout,
          stderr,
        });
      }
    });
  });
}

function buildRunArgs(objective) {
  return ["-m", "sovereign_claw.cli", "run", objective, "--json"];
}

function buildPreviewArgs(objective) {
  return ["-m", "sovereign_claw.cli", "run", objective, "--json", "--preview"];
}

function toPreviewPayload(result) {
  return {
    mode: "preview",
    supported: true,
    predicted_drift: result.final_drift ?? null,
    expected_halt_reason: result.reason ?? null,
    step_estimate:
      Array.isArray(result.steps) ? result.steps.length : result.steps ?? null,
    source_status: result.status ?? null,
    drift_trajectory: result.drift_trajectory ?? [],
    trace_id: result.trace_id ?? null,
    note: "Preview generated by CLI preview mode.",
  };
}

function toUnsupportedPreviewPayload(err) {
  return {
    mode: "preview",
    supported: false,
    predicted_drift: null,
    expected_halt_reason:
      "Preview mode is not currently supported by the Python CLI.",
    step_estimate: null,
    source_status: "preview-unavailable",
    drift_trajectory: [],
    trace_id: null,
    note:
      "Run execution remains available. Add --preview support in sovereign_claw.cli to enable predictive preview.",
    detail:
      typeof err?.stderr === "string" && err.stderr.trim()
        ? err.stderr.trim()
        : typeof err?.detail === "string"
        ? err.detail
        : typeof err?.error === "string"
        ? err.error
        : "No additional detail available.",
  };
}

app.get("/", (_req, res) => {
  res.json({
    service: "sovereign-claw-bridge",
    status: "ok",
    port: PORT,
  });
});

app.post("/run", async (req, res) => {
  const { objective } = req.body;

  if (!objective || typeof objective !== "string") {
    return res.status(400).json({ error: "Invalid objective" });
  }

  try {
    const result = await runCli(buildRunArgs(objective));
    res.json(result);
  } catch (err) {
    res.status(500).json(err);
  }
});

app.post("/preview", async (req, res) => {
  const { objective } = req.body;

  if (!objective || typeof objective !== "string") {
    return res.status(400).json({ error: "Invalid objective" });
  }

  try {
    const result = await runCli(buildPreviewArgs(objective));
    res.json(toPreviewPayload(result));
  } catch (err) {
    // Graceful fallback: preview remains visible and non-breaking
    res.json(toUnsupportedPreviewPayload(err));
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Sovereign bridge running on http://localhost:${PORT}`);
  console.log(`Repo root: ${repoRoot}`);
});