import express from "express";
import cors from "cors";
import { spawn } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 8787;
const MAX_TRACE_HISTORY = 50;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const traceHistory = [];

function pushTrace(entry) {
  traceHistory.unshift(entry);
  if (traceHistory.length > MAX_TRACE_HISTORY) {
    traceHistory.length = MAX_TRACE_HISTORY;
  }
}

function normalizeNumericString(value, fallback = "—") {
  if (value === null || value === undefined) return fallback;
  return String(value);
}

function normalizeStepCount(value, fallback = "—") {
  if (Array.isArray(value)) return String(value.length);
  if (value === null || value === undefined) return fallback;
  return String(value);
}

function runCli(args) {
  return new Promise((resolve, reject) => {
    const proc = spawn("python", args, {
      cwd: repoRoot,
      shell: false,
      env: {
        ...process.env,
        PYTHONPATH: path.join(repoRoot, "src"),
      },
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (data) => {
      stdout += data.toString();
    });

    proc.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    proc.on("error", (err) => {
      reject({
        error: "Failed to start CLI process",
        detail: err.message,
      });
    });

    proc.on("close", (code) => {
      if (code !== 0) {
        return reject({
          error: "CLI execution failed",
          code,
          stderr,
          stdout,
        });
      }

      try {
        resolve(JSON.parse(stdout));
      } catch {
        reject({
          error: "Invalid JSON from CLI",
          raw: stdout,
          stderr,
        });
      }
    });
  });
}

function buildRunArgs(objective) {
  return ["-m", "sovereign_claw.cli", "run", objective, "--json"];
}

function buildPreviewArgs(objective) {
  return ["-m", "sovereign_claw.cli", "run", objective, "--json", "--preview"];
}

function toPreviewPayload(result) {
  return {
    mode: "preview",
    supported: true,
    predicted_drift: result.final_drift ?? null,
    expected_halt_reason: result.reason ?? null,
    step_estimate:
      Array.isArray(result.steps) ? result.steps.length : result.steps ?? null,
    source_status: result.status ?? null,
    drift_trajectory: result.drift_trajectory ?? [],
    trace_id: result.trace_id ?? null,
    note: "Preview generated by CLI preview mode.",
    provider: result.provider ?? "runtime-local",
    policy_status: result.policy_status ?? "constraint-gated",
    preview: true,
    status: result.status ?? "preview",
    reason: result.reason ?? null,
    final_drift: result.final_drift ?? null,
    steps: result.steps ?? null,
  };
}

function toUnsupportedPreviewPayload(err) {
  return {
    mode: "preview",
    supported: false,
    predicted_drift: null,
    expected_halt_reason:
      "Preview mode is not currently supported by the Python CLI.",
    step_estimate: null,
    source_status: "preview-unavailable",
    drift_trajectory: [],
    trace_id: null,
    note:
      "Run execution remains available. Add --preview support in sovereign_claw.cli to enable predictive preview.",
    detail:
      typeof err?.stderr === "string" && err.stderr.trim()
        ? err.stderr.trim()
        : typeof err?.detail === "string"
        ? err.detail
        : typeof err?.error === "string"
        ? err.error
        : "No additional detail available.",
    provider: "preview-bridge",
    policy_status: "preview-unsupported",
    preview: true,
    status: "preview-unavailable",
    reason:
      "Preview mode is not currently supported by the Python CLI.",
  };
}

function normalizeRunTrace(payload, objective) {
  const runtimeStateAtTime =
    payload?.status === "halted"
      ? "halted"
      : payload?.status === "executed"
      ? "executed"
      : payload?.status === "error"
      ? "error"
      : "none";

  return {
    id: `run-${payload?.trace_id ?? Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}`,
    kind: "run",
    objective,
    controlStateAtTime: "executing",
    runtimeStateAtTime,
    traceId: payload?.trace_id ?? "No trace issued",
    reason: payload?.reason ?? payload?.error ?? "Governed execution recorded",
    provider: payload?.provider ?? "runtime-local",
    policyStatus: payload?.policy_status ?? "constraint-gated",
    finalDrift: normalizeNumericString(payload?.final_drift),
    steps: normalizeStepCount(payload?.steps),
    createdAt: new Date().toISOString(),
    previewSummary: payload?.reason ?? "Governed runtime result recorded.",
    payload,
  };
}

function normalizePreviewTrace(payload, objective) {
  const supported = payload?.supported !== false;

  return {
    id: `preview-${payload?.trace_id ?? Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}`,
    kind: "preview",
    objective,
    controlStateAtTime: "preview",
    runtimeStateAtTime:
      payload?.status === "error"
        ? "error"
        : payload?.source_status === "halted" || payload?.preview === true
        ? "halted"
        : "none",
    traceId: payload?.trace_id ?? "No trace issued",
    reason:
      payload?.expected_halt_reason ??
      payload?.reason ??
      payload?.error ??
      "Preview generated",
    provider: payload?.provider ?? "preview-bridge",
    policyStatus:
      payload?.policy_status ??
      (supported ? "preview-supported" : "preview-unsupported"),
    finalDrift: normalizeNumericString(
      payload?.predicted_drift ?? payload?.final_drift
    ),
    steps: normalizeStepCount(payload?.step_estimate ?? payload?.steps),
    createdAt: new Date().toISOString(),
    previewSummary:
      payload?.note ??
      payload?.detail ??
      (supported
        ? "Preview generated by CLI preview mode."
        : "Preview generated by bridge fallback."),
    payload,
  };
}

app.get("/", (_req, res) => {
  res.json({
    service: "sovereign-claw-bridge",
    status: "ok",
    port: PORT,
    trace_count: traceHistory.length,
  });
});

app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    service: "sovereign-claw-bridge",
    trace_count: traceHistory.length,
  });
});

app.get("/traces", (_req, res) => {
  res.json({
    traces: traceHistory,
    count: traceHistory.length,
  });
});

app.post("/run", async (req, res) => {
  const { objective } = req.body;

  if (!objective || typeof objective !== "string") {
    return res.status(400).json({ error: "Invalid objective" });
  }

  try {
    const result = await runCli(buildRunArgs(objective));
    pushTrace(normalizeRunTrace(result, objective));
    res.json(result);
  } catch (err) {
    const payload = {
      status: "error",
      error:
        typeof err?.error === "string" ? err.error : "CLI execution failed",
      detail: typeof err?.detail === "string" ? err.detail : undefined,
      stderr: typeof err?.stderr === "string" ? err.stderr : undefined,
      stdout: typeof err?.stdout === "string" ? err.stdout : undefined,
      preview: false,
      provider: "runtime-local",
      policy_status: "constraint-gated",
    };

    pushTrace(normalizeRunTrace(payload, objective));
    res.status(500).json(payload);
  }
});

app.post("/preview", async (req, res) => {
  const { objective } = req.body;

  if (!objective || typeof objective !== "string") {
    return res.status(400).json({ error: "Invalid objective" });
  }

  try {
    const result = await runCli(buildPreviewArgs(objective));
    const payload = toPreviewPayload(result);
    pushTrace(normalizePreviewTrace(payload, objective));
    res.json(payload);
  } catch (err) {
    const payload = toUnsupportedPreviewPayload(err);
    pushTrace(normalizePreviewTrace(payload, objective));
    res.json(payload);
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Sovereign bridge running on http://localhost:${PORT}`);
  console.log(`Repo root: ${repoRoot}`);
  console.log(`Trace capacity: ${MAX_TRACE_HISTORY}`);
});